### ISSUE TITLE
 BaseViewModel를 찾을 수 없어요

### ISSUE THREAD

**Issue by clonekim** [benimario/parayo-android#1]
SignupViewModel작성 시 BaseViewModel 은 어디서 가져오는건가요?
net.codephobia 의 패키지는 못찾아오는데 확인 부탁드려요.

**Comment by clonekim** [comment]
해결했습니다. 
anko를 못찾아서 다른 디펜던시에 오류가 생긴겁니다.
jcenter에 0.10.8이 있는데 못찾은거에요.

**Comment by NaNupsida** [comment]
코틀린을 처음 접해보는 초보자 입니다. (자바도 모르고... 일단 코딩중..)

책따라서 111쪽 작업하였는데요 SignupViewModel.kt 에서 import net.codephobia.~~~
저도 이부분에서 에러가 나는데 해결을 못하고 있습니다.

혹시 답변 남겨주신걸 보고 고민을 해보았는데요 초보자라서... 답변 내용만 보고서는 이해가 안되어 답글을 남기며... git도 처음이라... 이렇게 남기는게 맞는건지 매우 혼란스럽습니다만..

혹시 조금 자세히 풀어서 알려주실수 있을런지요..?

**Comment by clonekim** [comment]
아 그러시군요.
자바에서 라이브러리 사용 시에 관련된 라이브러리 (의존성을) 인터넷에서 다운로드 하는데요.
라이브러리가 있는 곳을 보통 리포지토리 라고 불러요
메이븐, jcenter뭐 이런 곳이죠.

그리고 리포지토리를 명시한 파일 이름이 build.gradle인데요
특이점은 ankomvvm 가 메이븐에 없고 jcenter에는 있어요
그래서 build.gradle에서

repositories {
       jcenter()
       google()
}
위의 순서를 바꿔보거나 캐시를 지우고  별의별 방법을 다 썻어요
위에서 말한 라이브러리는 현재 접속 자의 홈디렉토리의 .m2라는 디렉토리에 저장됩니다
그러니 그 디렉토리를 지우고  개발툴에서 gradle 에서 새로고침을 하면 다시 인터넷에서
내려 받게 됩니다.
문제는 jcenter가 종종 다운되는 경우가 있더라구요 그럴때는 해당 라이브러리를 못받겠죠.


2020년 7월 31일 (금) 오후 1:41, NaNupsida <notifications@github.com>님이 작성:

**Comment by clonekim** [comment]
아 그러시군요.
자바에서 라이브러리 사용 시에 관련된 라이브러리 (의존성을) 인터넷에서 다운로드 하는데요.
라이브러리가 있는 곳을 보통 리포지토리 라고 불러요
메이븐, jcente r뭐 이런 곳이죠.

그리고 리포지토리를 명시한 파일 이름이 build.gradle인데요 
특이점은 ankomvvm 가 메이븐에 없고 jcenter에는 있어요
그래서 build.gradle에서 

repositories {
       jcenter()
       google()     
}
위의 순서를 바꿔보거나 캐시를 지우고  별의별 방법을 다 썻어요
위에서 말한 라이브러리는 현재 접속 자의 홈디렉토리의 .m2라는 디렉토리에 저장됩니다
그러니 그 디렉토리를 지우고  개발툴에서 gradle 에서 새로고침을 하면 다시 인터넷에서
내려 받게 됩니다.
문제는 jcenter가 종종 다운되는 경우가 있더라구요 그럴때는 해당 라이브러리를 못받겠죠.
