### ISSUE TITLE
같은문제에 봉착하였는데 도움을 받을수 있을까요?

### ISSUE THREAD

**Issue by NaNupsida** [benimario/parayo-android#2]
코틀린을 처음 접해보는 초보자 입니다. (자바도 모르고... 일단 코딩중..)

책따라서 111쪽 작업하였는데요 SignupViewModel.kt 에서 import net.codephobia.~~~
저도 이부분에서 에러가 나는데 해결을 못하고 있습니다.

혹시 답변 남겨주신걸 보고 고민을 해보았는데요 초보자라서... 답변 내용만 보고서는 이해가 안되어 답글을 남기며... git도 처음이라... 이렇게 남기는게 맞는건지 매우 혼란스럽습니다만..

혹시 조금 자세히 풀어서 알려주실수 있을런지요..?

**Comment by NaNupsida** [comment]
문제) 
일단 책의 내용대로 따라하다가 막힌 부분은 112쪽  SignupViewModel.kt 를 작성후 
import net.codephobia.ankomvvm.lifecycle.BaseViewModel 여기서 Unresolved reference: net이 되어집니다. 

해결) 소스코드 다운받아서 확인하였음.
111쪽  dependencies 추가할때 아랫코드도 같이 추가해 주어야 인식됨.

implementation 'com.github.benimario:ankomvvm:0.1.0'

의존성 추가할때 윗코드도 같이 넣어줘야 함. 
----------------------------------------------------------------------------------------------------------------------
윗문제는 해결되었으나 SignupViewModel.kt 내용중 app: Apllication 부분에 또Unresolved reference: Application이라 나옴..

**Comment by benimario** [comment]
안녕하세요.
답변이 늦어 죄송합니다.

먼저 말씀해주셨던 문제는 책에서 너무 사소하게 다루고 넘어가 많은 분들이 혼란스러워하시는 것 같습니다. 죄송합니다.
재판이 인쇄될 때 꼭 개선하도록 하겠습니다.

두번째 말씀해주신 문제는 다음 이미지를 참고하여
3번째 줄 android.app.Application 이 임포트 되어 있는지 확인 부탁드립니다.

![image](https://user-images.githubusercontent.com/18565570/89025836-7caa1b00-d362-11ea-99da-bab1c15a3482.png)

**Comment by NaNupsida** [comment]
안녕하세요~ 답변이 늦었습니다.~

2번째 문제는 오타로 인해 인식이 안되었습니다. 다시 진행해 보겠습니다.
